// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH06iD7aSoUVpiREQTb-PlRWSZAq2VCwQ',
    appId: '1:689870563559:web:1e2b0313749b0421501a42',
    messagingSenderId: '689870563559',
    projectId: 'game-f36e1',
    authDomain: 'game-f36e1.firebaseapp.com',
    storageBucket: 'game-f36e1.appspot.com',
    measurementId: 'G-HJMSGHE68E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrn24l2GWQa6Kx5mqdeIZ76pPStqq7WAA',
    appId: '1:689870563559:android:2536224712dcfa28501a42',
    messagingSenderId: '689870563559',
    projectId: 'game-f36e1',
    storageBucket: 'game-f36e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn50E79l2RdH-tTxCJFWh8uWJbMlGGRBI',
    appId: '1:689870563559:ios:1a647fe6982ee1a7501a42',
    messagingSenderId: '689870563559',
    projectId: 'game-f36e1',
    storageBucket: 'game-f36e1.appspot.com',
    iosBundleId: 'com.example.appArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn50E79l2RdH-tTxCJFWh8uWJbMlGGRBI',
    appId: '1:689870563559:ios:faf54f77d6a39ba1501a42',
    messagingSenderId: '689870563559',
    projectId: 'game-f36e1',
    storageBucket: 'game-f36e1.appspot.com',
    iosBundleId: 'com.example.appArchitecture.RunnerTests',
  );
}
